### ISSUE TITLE
wire library

### ISSUE THREAD

**Issue by rudyspies** [jlesech/24C04-08-16#1]
Hi, I've been writing my own routines for sequential reading and writing to the 24C04. I quickly discovered that the <WIRE> library limits the page size to 32 bytes for historical reasons. As a result, the code also includes a very long waiting period after writing bytes: about 7.2ms for 30bytes. 
So what <WIRE> does on a sequential write is:
START <Slave addr>, <addr H> <addr L> <Byte1> <byte2> ....<byte n> ..............long wait..........<slave addr> STOP
This is again for historical reasons, using EEPROMS. The EERAM doesn't have that limitation and the whole memory can be filled up as fast as the processor can supply (limitation of 1MHz I2C clock rate). I've looked at the <WIRE> source file but I can't seem to find where this delay is generated. Can you maybe assist?

**Comment by jlesech** [comment]
Hello! This delay is introduced at line [296](https://github.com/jlesech/Eeprom24C04_08_16/blob/7332b292b0f47ba29461515abd146c0a5afb8806/Eeprom24C04_16.cpp#L296).
